# Generated by Django 3.2.7 on 2021-10-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producte',
            name='sku',
            field=models.CharField(max_length=9),
        ),
    ]
