# Generated by Django 3.2.7 on 2021-10-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazin',
            name='pret',
            field=models.IntegerField(default=0),
        ),
    ]
