# Generated by Django 3.2.7 on 2021-10-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0002_alter_producte_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producte',
            name='sku',
            field=models.CharField(max_length=8),
        ),
    ]
