# Generated by Django 3.2.7 on 2021-10-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0002_magazin_pret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazin',
            name='SKU',
            field=models.CharField(default='8061CEE71', max_length=8, unique=True),
        ),
    ]
