# Generated by Django 3.2.7 on 2021-10-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0003_alter_magazin_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazin',
            name='SKU',
            field=models.CharField(default='54A7AC00', max_length=8, unique=True),
        ),
    ]
