# Generated by Django 3.2.7 on 2021-10-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0004_alter_magazin_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazin',
            name='SKU',
            field=models.CharField(default='121C63E8', max_length=8),
        ),
    ]
