# Generated by Django 3.2.7 on 2021-10-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0005_alter_magazin_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazin',
            old_name='add_at',
            new_name='Add_at',
        ),
        migrations.RenameField(
            model_name='magazin',
            old_name='descriere',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='magazin',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='magazin',
            old_name='photo1',
            new_name='Photo1',
        ),
        migrations.RenameField(
            model_name='magazin',
            old_name='photo2',
            new_name='Photo2',
        ),
        migrations.RenameField(
            model_name='magazin',
            old_name='photo3',
            new_name='Photo3',
        ),
        migrations.RenameField(
            model_name='magazin',
            old_name='pret',
            new_name='Price',
        ),
        migrations.AlterField(
            model_name='magazin',
            name='SKU',
            field=models.CharField(default='13830976', max_length=8),
        ),
    ]
