# Generated by Django 3.2.7 on 2021-10-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0006_auto_20211003_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazin',
            old_name='Add_at',
            new_name='add_at',
        ),
        migrations.RenameField(
            model_name='magazin',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='magazin',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='magazin',
            old_name='Photo1',
            new_name='photo1',
        ),
        migrations.RenameField(
            model_name='magazin',
            old_name='Photo2',
            new_name='photo2',
        ),
        migrations.RenameField(
            model_name='magazin',
            old_name='Photo3',
            new_name='photo3',
        ),
        migrations.RenameField(
            model_name='magazin',
            old_name='Price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='magazin',
            name='SKU',
        ),
        migrations.AddField(
            model_name='magazin',
            name='sku',
            field=models.CharField(default='3F00863B', max_length=8),
        ),
    ]
