# Generated by Django 3.2.7 on 2021-10-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0007_auto_20211003_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazin',
            name='sku',
            field=models.CharField(max_length=8),
        ),
    ]
